/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get me */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                center?: {
                                    id: string;
                                    email: string;
                                    name: string;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                                user?: {
                                    id: string;
                                    email: string;
                                    /** @default null */
                                    username: string | null;
                                    /** @default null */
                                    firstName: string | null;
                                    /** @default null */
                                    lastName: string | null;
                                    centerId: string;
                                    role: "ADMIN" | "TEACHER" | "STUDENT";
                                    /** @default null */
                                    phoneNumber: string | null;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/center/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register a center */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                center: {
                                    id: string;
                                    email: string;
                                    name: string;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/center/signIn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign in a center */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        idToken: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                token: string;
                                center: {
                                    id: string;
                                    email: string;
                                    name: string;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/center/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get current center */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                center: {
                                    id: string;
                                    email: string;
                                    name: string;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Update a user */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        userId: string;
                        username?: string;
                        firstName?: string;
                        lastName?: string;
                        phoneNumber?: string;
                        role?: "ADMIN" | "TEACHER" | "STUDENT";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                user: {
                                    id: string;
                                    email: string;
                                    /** @default null */
                                    username: string | null;
                                    /** @default null */
                                    firstName: string | null;
                                    /** @default null */
                                    lastName: string | null;
                                    centerId: string;
                                    role: "ADMIN" | "TEACHER" | "STUDENT";
                                    /** @default null */
                                    phoneNumber: string | null;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        /** @description Create a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                        role: "ADMIN" | "TEACHER" | "STUDENT";
                        username?: string;
                        firstName?: string;
                        lastName?: string;
                        phoneNumber?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                user: {
                                    id: string;
                                    email: string;
                                    /** @default null */
                                    username: string | null;
                                    /** @default null */
                                    firstName: string | null;
                                    /** @default null */
                                    lastName: string | null;
                                    centerId: string;
                                    role: "ADMIN" | "TEACHER" | "STUDENT";
                                    /** @default null */
                                    phoneNumber: string | null;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get list of users */
        get: {
            parameters: {
                query: {
                    take: number;
                    cursor?: string;
                    searchString?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                nodes: {
                                    user: {
                                        id: string;
                                        email: string;
                                        /** @default null */
                                        username: string | null;
                                        /** @default null */
                                        firstName: string | null;
                                        /** @default null */
                                        lastName: string | null;
                                        centerId: string;
                                        role: "ADMIN" | "TEACHER" | "STUDENT";
                                        /** @default null */
                                        phoneNumber: string | null;
                                        createdAt: unknown;
                                        updatedAt: unknown;
                                    };
                                    classes: {
                                        id: string;
                                        name: string;
                                        /** @default null */
                                        description: string | null;
                                        createdAt: unknown;
                                        updatedAt: unknown;
                                    }[];
                                }[];
                                pageInfo: {
                                    hasNextPage: boolean;
                                    cursor?: string;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/signIn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign in a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                token: string;
                                user: {
                                    id: string;
                                    email: string;
                                    /** @default null */
                                    username: string | null;
                                    /** @default null */
                                    firstName: string | null;
                                    /** @default null */
                                    lastName: string | null;
                                    centerId: string;
                                    role: "ADMIN" | "TEACHER" | "STUDENT";
                                    /** @default null */
                                    phoneNumber: string | null;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/class/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Update a class */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        classId: string;
                        name?: string;
                        description?: string;
                        addMembers?: string[];
                        removeMembers?: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                class: {
                                    id: string;
                                    name: string;
                                    /** @default null */
                                    description: string | null;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        /** @description Create a class */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        description?: string;
                        classMember: string[];
                        centerId: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                class: {
                                    id: string;
                                    name: string;
                                    /** @default null */
                                    description: string | null;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/class/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a class */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                class: {
                                    id: string;
                                    name: string;
                                    /** @default null */
                                    description: string | null;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/class/{classId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a class */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/class/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get class list */
        get: {
            parameters: {
                query: {
                    take: number;
                    cursor?: string;
                    centerId: string;
                    searchString?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                nodes: {
                                    class: {
                                        id: string;
                                        name: string;
                                        /** @default null */
                                        description: string | null;
                                        createdAt: unknown;
                                        updatedAt: unknown;
                                    };
                                    members: {
                                        id: string;
                                        email: string;
                                        /** @default null */
                                        username: string | null;
                                        /** @default null */
                                        firstName: string | null;
                                        /** @default null */
                                        lastName: string | null;
                                        centerId: string;
                                        role: "ADMIN" | "TEACHER" | "STUDENT";
                                        /** @default null */
                                        phoneNumber: string | null;
                                        createdAt: unknown;
                                        updatedAt: unknown;
                                    }[];
                                }[];
                                pageInfo: {
                                    hasNextPage: boolean;
                                    cursor?: string;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create an exercise */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        subTypeId: string;
                        name: string;
                        content: unknown;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                exercise: {
                                    id: string;
                                    name: string;
                                    content: unknown;
                                    subTypeId: string;
                                    /** @default null */
                                    centerId: string | null;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an exercise with id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                exercise: {
                                    id: string;
                                    name: string;
                                    content: unknown;
                                    subTypeId: string;
                                    /** @default null */
                                    centerId: string | null;
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                                subType: {
                                    id: string;
                                    name: string;
                                    /** @default null */
                                    description: string | null;
                                    exerciseType: "READING" | "LISTENING" | "WRITING" | "SPEAKING";
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete an exercise */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise/subtype/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get list of exercises sub types */
        get: {
            parameters: {
                query: {
                    type: "READING" | "LISTENING" | "WRITING" | "SPEAKING";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                exerciseSubTypes: {
                                    id: string;
                                    name: string;
                                    /** @default null */
                                    description: string | null;
                                    exerciseType: "READING" | "LISTENING" | "WRITING" | "SPEAKING";
                                    createdAt: unknown;
                                    updatedAt: unknown;
                                }[];
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get list of exercises */
        get: {
            parameters: {
                query: {
                    take: number;
                    cursor?: string;
                    type?: "READING" | "LISTENING" | "WRITING" | "SPEAKING";
                    subTypeIds?: string[];
                    isPublic: boolean;
                    searchString?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                nodes: {
                                    subType: {
                                        id: string;
                                        name: string;
                                        /** @default null */
                                        description: string | null;
                                        exerciseType: "READING" | "LISTENING" | "WRITING" | "SPEAKING";
                                        createdAt: unknown;
                                        updatedAt: unknown;
                                    };
                                    exercise: {
                                        id: string;
                                        name: string;
                                        content: unknown;
                                        subTypeId: string;
                                        /** @default null */
                                        centerId: string | null;
                                        createdAt: unknown;
                                        updatedAt: unknown;
                                    };
                                }[];
                                pageInfo: {
                                    hasNextPage: boolean;
                                    cursor?: string;
                                };
                            };
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Center */
        Center: {
            id: string;
            email: string;
            name: string;
            createdAt: unknown;
            updatedAt: unknown;
        };
        /** RegisterCenterInput */
        RegisterCenterInput: {
            email: string;
            name: string;
        };
        /** SignInCenterInput */
        SignInCenterInput: {
            idToken: string;
        };
        /** UserRole */
        UserRole: "ADMIN" | "TEACHER" | "STUDENT";
        /** User */
        User: {
            id: string;
            email: string;
            /** @default null */
            username: string | null;
            /** @default null */
            firstName: string | null;
            /** @default null */
            lastName: string | null;
            centerId: string;
            role: "ADMIN" | "TEACHER" | "STUDENT";
            /** @default null */
            phoneNumber: string | null;
            createdAt: unknown;
            updatedAt: unknown;
        };
        /** CreateUserInput */
        CreateUserInput: {
            email: string;
            password: string;
            role: "ADMIN" | "TEACHER" | "STUDENT";
            username?: string;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
        };
        /** GetUserListInput */
        GetUserListInput: {
            take: number;
            cursor?: string;
            searchString?: string;
        };
        /** SignInUserInput */
        SignInUserInput: {
            email: string;
            password: string;
        };
        /** UpdateUserInput */
        UpdateUserInput: {
            userId: string;
            username?: string;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
            role?: "ADMIN" | "TEACHER" | "STUDENT";
        };
        /** Class */
        Class: {
            id: string;
            name: string;
            /** @default null */
            description: string | null;
            createdAt: unknown;
            updatedAt: unknown;
        };
        /** GetClassListInput */
        GetClassListInput: {
            take: number;
            cursor?: string;
            centerId: string;
            searchString?: string;
        };
        /** UpdateClassInput */
        UpdateClassInput: {
            classId: string;
            name?: string;
            description?: string;
            addMembers?: string[];
            removeMembers?: string[];
        };
        /** ReadingQuestionOption */
        ReadingQuestionOption: {
            content: string;
            order: number;
            value: string;
        };
        /** ReadingExerciseQuestion */
        ReadingExerciseQuestion: {
            content: string;
            correctAnswer: string;
            order: number;
            options: {
                content: string;
                order: number;
                value: string;
            }[];
        };
        /** ReadingExerciseTask */
        ReadingExerciseTask: {
            instructions: string;
            questions: {
                content: string;
                correctAnswer: string;
                order: number;
                options: {
                    content: string;
                    order: number;
                    value: string;
                }[];
            }[];
        };
        /** ReadingExercise */
        ReadingExercise: {
            title: string;
            content: string;
            tasks: {
                instructions: string;
                questions: {
                    content: string;
                    correctAnswer: string;
                    order: number;
                    options: {
                        content: string;
                        order: number;
                        value: string;
                    }[];
                }[];
            }[];
        };
        /** ReadingExerciseType */
        ReadingExerciseType: "Multiple choice" | "True/False/Not Given";
        /** ExerciseType */
        ExerciseType: "READING" | "LISTENING" | "WRITING" | "SPEAKING";
        /** Exercise */
        Exercise: {
            id: string;
            name: string;
            content: unknown;
            subTypeId: string;
            /** @default null */
            centerId: string | null;
            createdAt: unknown;
            updatedAt: unknown;
        };
        /** ExerciseSubType */
        ExerciseSubType: {
            id: string;
            name: string;
            /** @default null */
            description: string | null;
            exerciseType: "READING" | "LISTENING" | "WRITING" | "SPEAKING";
            createdAt: unknown;
            updatedAt: unknown;
        };
        /** GetExerciseListInput */
        GetExerciseListInput: {
            take: number;
            cursor?: string;
            type?: "READING" | "LISTENING" | "WRITING" | "SPEAKING";
            subTypeIds?: string[];
            isPublic: boolean;
            searchString?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
